ALTER TABLE reserva DROP CONSTRAINT IF EXISTS chk_reserva_estado;
ALTER TABLE reserva ADD CONSTRAINT chk_reserva_estado 
CHECK (estado IN ('PENDIENTE', 'PAGADA', 'CONFIRMADA', 'RECHAZADA', 'CANCELADA', 'NO_PRESENTADO'));