ALTER TABLE persona 
ADD COLUMN fondos_totales DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN fondos_actuales DECIMAL(10, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE viaje DROP CONSTRAINT IF EXISTS chk_viaje_estado;
ALTER TABLE viaje ADD CONSTRAINT chk_viaje_estado 
CHECK (estado IN ('INICIADO', 'PENDIENTE', 'EN_CURSO', 'FINALIZADO', 'CANCELADO'));