ALTER TABLE viaje ADD COLUMN IF NOT EXISTS fecha_cancelacion TIMESTAMP NULL;
ALTER TABLE viaje_recurrente ADD COLUMN IF NOT EXISTS fecha_cancelacion TIMESTAMP NULL;
ALTER TABLE reserva ADD COLUMN IF NOT EXISTS fecha_cancelacion TIMESTAMP NULL;