spring.application.name=backend
spring.config.import=optional:file:../.env[.properties],optional:file:./.env[.properties]
stripe.api.key=${STRIPE_API_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}
app.frontend.url=http://localhost:5173

# Configuración SMTP (Por defecto: Mailpit para local)
spring.mail.host=${SMTP_HOST:localhost}
spring.mail.port=${SMTP_PORT:1025}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:false}

compicar.mail.from=${MAIL_FROM:no-reply@compicar.com}