spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/compicar
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

jwt:
  secret: P5KqM1v1fcIbmujHih5kZQxEvRKc4Q2pw6nd6m1eNUk=
  expiration: 3600000
