spring.application.name=backend
spring.config.import=optional:file:../.env[.properties],optional:file:./.env[.properties]
stripe.api.key=${STRIPE_API_KEY:}
# Esta la obtendremos más adelante para los Webhooks
stripe.webhook.secret=whsec_...